### ISSUE TITLE
Question with open loop control command setting

### ISSUE THREAD

**Issue by HappySamuel** [ecostech/roboteq_diff_driver#10]
Hi 

I am curious on how to get the following value:

![Screenshot from 2020-03-27 11-38-24](https://user-images.githubusercontent.com/18137963/77719275-e1094680-701f-11ea-806b-bec8846ed3a3.png)

Best,
Samuel

**Comment by attermann** [comment]
Hi Samuel,

Those are scaling factors which basically make controller motor power (0-1000) scale linearly with desired motor speed (rpms).  The value "82.0" is maximum motor speed (rpm) which was hard-coded during initial development but never made configurable since focus was on closed-loop mode.  I will be pushing an update shortly that makes both maximum motor speed and maximum motor current configurable .

Regards,

Chad.
