### ISSUE TITLE
CPU usage 100% when it's run in NVIDIA embedded system

### ISSUE THREAD

**Issue by sankhakarfa** [ecostech/roboteq_diff_driver#12]
Hi I am using roboteq diff driver and I am getting higher CPU usage when I am running it.
The issue gets fixed if I uncomment
```
        ros::Rate loop_rate(100);
        loop_rate.sleep();
```
But the messages now get delayed.
I just want CR values at 10hz so what should I change in the code?

**Comment by attermann** [comment]
Hi @sankhakarfa.  You can not run the main loop at 10 Hz because it is polling the serial port one character at a time, so it needs to be called many times every 100 ms to fully read the output stream from the motor controller.  You could try a sleep of 1 ms to see if that improves cpu usage without delaying odom updates.  I have also been told that removing the `if (controller.available())` conditional in MainNode::odom_loop() can improve cpu usage although I have yet to confirm that.
