### ISSUE TITLE
Loop wo/ delay 

### ISSUE THREAD

**Issue by ahmediv** [ecostech/roboteq_diff_driver#13]
The main loop running without delay causing more CPU consumption than required  

https://github.com/ecostech/roboteq_diff_driver/blob/eb4e90cfad7e7dc423bab2d5fee9e1337d930a02/roboteq_diff_driver/src/driver.cpp#L888

**Comment by GoldenZephyr** [comment]
For anyone coming across this in the future, the fix is not necessarily as simple as just putting the sleep back in. As discussed in #12 , the driver reads incoming serial data in a weird way. At most one byte is read per iteration of this loop. So having this sleep means that data is read very slowly when it's ready. I believe a proper fix would involve putting this sleep in *and* changing the `odom_loop` function to read all available bytes instead of just 1.

**Comment by attermann** [comment]
@ahmediv I don't currently have a Roboteq connected to a CPU board so I can't verify this fix, but I suggest in addition to un-commenting
