### ISSUE TITLE
Inverted Behavior with XDC2460 Driver

### ISSUE THREAD

**Issue by mhaboali** [ecostech/roboteq_diff_driver#9]
Hi,

I'm using roboteq_diff_driver with my [XDC2460](https://www.superdroidrobots.com/shop/item.aspx/roboteq-xdc2460-2x150a-60v-motor-controller-with-encoder-input/2233/) driver, it worked but there was strange behavior. 

When sending forward motion command via /cmd_vel: linear: x: 3.0 and all other components are zeros, the right wheels move backward, but the left wheels move forward.

And when sending turn right command via /cmd_vel: angular: z: 3.0 and all other components are zeros, the left and right wheels move in one direction(forward).

Thanks!

**Comment by attermann** [comment]
Hello,

Wondering if you got this figured out. Let me know if you're still having trouble with motor direction.

**Comment by mhaboali** [comment]
Hello,

Unfortunately, it's not figured properly until now and the odometry data is very wrong. Could you help me to fix it?

Thanks!

**Comment by attermann** [comment]
Sure I'll do what I can.  Are you running in open or closed loop mode?  Will you send log output from your tests so that we can see what is being read from and written to the motor controller?

**Comment by attermann** [comment]
I suspect I know what your issue is.  The driver expects that when it issues positive speed/power commands to each motor, that will translate into forward motion at that motor.  If you are getting the opposite direction at a motor, you simply need to swap the positive and negative terminals to that motor at the controller.

You also need to be sure that the right motor is connected to channel 1 on your controller (M1), and the left motor is connected to channel 2 (M2).

In my own configuration for example, for the right motor I have the positive motor lead connected to M1+ and the negative motor lead connected to M1-, but for the left motor I have the negative motor lead connected to M2+ and the positive motor lead connected to M2-.  With positive speed/power commands to the motors this results in clockwise rotation at the right motor, counter-clockwise rotation at the left motor, and forward translation of the robot.

Let me know if this resolves your problem.

**Comment by mhaboali** [comment]
Thanks so much for your great comment, I really appreciate it!

I'm so sorry for the delay but the things got almost frozen here because of COVID-19 and when I get a chance, I'll let you know what's going on here with me

Please keep yourself safe!
